on:
    push:
        branches:
            - "main"

jobs:
    deployheroku:
        name: Deploy to dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  ref: ${{ github.ref }}

            - name: Set up Docker Buildx 🚀
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub 🚢
              uses: docker/login-action@v3
              with:
                  username: "${{ secrets.DOCKER_USERNAME }}"
                  password: "${{ secrets.DOCKER_PASSWORD }}"

            - name: Set up Docker CLI
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  tags: acandh46/pwr-x:latest
                  cache-from: type=registry,ref=acandh46/pwr-x:buildcache
                  cache-to: type=registry,ref=acandh46/pwr-x:buildcache,mode=max
